services:
  dockyard:
    image: kareemwaheed/dockyard:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./secret-keys:/app/secret-keys:ro
      - ./scripts:/app/scripts:ro
      - data:/data
      - repos:/app/repos

volumes:
  repos:
  data:
